### ISSUE TITLE
Some error at GetFileList under Python 3.5

### ISSUE THREAD

**Issue by 0b1Kenobi** [ufilesdk-dev/ufile-pythonsdk#2]
When using UFile SDK under Python3.5, i got some error, hope can fix these problem.:

- ### {Content-Length: 0} must be of type str or bytes, not <class 'int'>

  #### err msg
  ```
  [2018-04-03 10:53:37,444, ERROR]: httprequest.py-190: send request error:Value for header {Content-Length: 0} must be of type str or bytes, not <class 'int'>
  ```

  It's located in ```getufilelist.py > GetFileList > getfilelist```,  easy fix:

  ```python
  def getfilelist(...):
      ...
      header['Content-Length'] = '0'
      ...
  ```

- ### NameError: name 'unicode' is not defined

  #### err msg

  ```
  File "ufile/getufilelist.py", line 51, in getfilelist
      if prefix is not None and (isinstance(prefix, str) or isinstance(marker, unicode)):
     NameError: name 'unicode' is not defined
  ```
  Python 3 renamed the unicode type to str, the old str type has been replaced by bytes.

**Comment by lizhenfu100** [comment]
We have fixed it,thanks :smile:
