### ISSUE TITLE
Can't get numberic prefix even perfix is string type.

### ISSUE THREAD

**Issue by 0b1Kenobi** [ufilesdk-dev/ufile-pythonsdk#3]
## Can't get numberic prefix even perfix is string type.

When i had a numberic prefix on my bucket, i can't got it by sdk but got it on website dashboard.

ez code like this: ```getfilelist(prefix='1024') ```,  but return empty dataset.

**Comment by lizhenfu100** [comment]
You should use the function like this: `getfilelist(bucket,'1024')`
